# Runxi's second MacBook Pro. Everything here is true of THIS machine, not of
# "a Mac": the apps actually installed on it and its dock.
#
# Settings that should hold on every Mac live in ./default.nix.
#
# Account name is `rshen`, matching every Linux machine in the fleet. It is
# threaded in from mkDarwin rather than written here, so nothing under homes/
# or modules/ names it.
#
# Deliberately thinner than ./runxi-mbp.nix. That host also carries a dsh-web
# launchd agent, a CODEX_CA_CERTIFICATE pointing at a pem generated by its own
# Obsidian install, and a Nutstore symlink -- all of which depend on imperative
# state that does not exist here. Each is a small edit away if this machine ever
# grows the same setup. (Zotero needs no Nutstore client on either Mac: it syncs
# attachments over WebDAV straight to dav.jianguoyun.com.)
{ config, pkgs, lib, user, ... }:

{
  imports = [
    # Purdue OneDrive: the ~/Purdue_OneDrive alias and the tombstone that keeps
    # "OneDrive - purdue.edu" from ever appearing. Shared with runxi-mbp, which
    # signs into the same tenant.
    #
    # This Mac has never had OneDrive installed, which is the best case for the
    # tombstone: it lands before OneDrive first runs, so the badly-named folder
    # never appears even once. Switch BEFORE signing in.
    ../../modules/darwin/onedrive-purdue.nix
  ];

  # This Mac runs Determinate Nix, which manages its own daemon; nix-darwin must
  # keep its hands off. A machine installed with the upstream Nix installer
  # wants `true` instead, which is why this is per-host rather than shared.
  #
  # Consequence worth remembering: with this false, nix-darwin writes no
  # /etc/nix/nix.conf at all, so the substituters, trusted-users and
  # experimental-features declared in ./default.nix are INERT on this host.
  # They have to be set in Determinate's own /etc/nix/nix.custom.conf instead.
  nix.enable = false;

  # Apps installed by Homebrew rather than Nix -- per-machine by nature. A
  # trimmed subset of runxi-mbp's list; see that file's casks.nix.
  homebrew.casks = pkgs.callPackage ../../modules/darwin/casks-rshen-mbp.nix { };

  # Fully declarative. Omitting this would evaluate cleanly and then wipe the
  # dock on activation -- the assertion in modules/darwin/home-manager.nix
  # exists to catch exactly that.
  #
  # The /Applications entries are casks, which Homebrew installs during the same
  # activation that runs dockutil, so on a FIRST switch some may not exist yet
  # and are simply skipped. A second `build-switch` settles it.
  local.dock.entries = [
    { path = "/Applications/Slack.app/"; }
    { path = "/System/Applications/Messages.app/"; }
    { path = "${pkgs.alacritty}/Applications/Alacritty.app/"; }
    { path = "/System/Applications/Music.app/"; }
    { path = "/Applications/Google Chrome.app/"; }
    { path = "/Applications/Visual Studio Code.app/"; }
    { path = "/Applications/Claude.app/"; }
    {
      path = "${config.users.users.${user}.home}/.local/share/";
      section = "others";
      options = "--sort name --view grid --display folder";
    }
    # runxi-mbp stacks ~/.local/share/downloads here; that path does not exist
    # on this machine, and dockutil cannot add what is not there.
    {
      path = "${config.users.users.${user}.home}/Downloads";
      section = "others";
      options = "--sort dateadded --view grid --display stack";
    }
  ];
}
