# Runxi's MacBook Pro. Everything here is true of THIS machine, not of "a Mac":
# the apps actually installed on it, its dock, its cloud-sync accounts, and the
# launchd agents for tools that live outside the Nix store on this box.
#
# Settings that should hold on every Mac live in ./default.nix.
#
# Account name is `runxishen` (uid 501, pre-dates the fleet's `rshen`
# convention). It is threaded in from mkDarwin rather than written here, so
# renaming this machine later means editing one string in flake.nix.
{ config, pkgs, lib, user, ... }:

{
  # This Mac runs Determinate Nix, which manages its own daemon; nix-darwin must
  # keep its hands off. A machine installed with the upstream Nix installer
  # wants `true` instead, which is why this is per-host rather than shared.
  # Verified: /run/current-system/etc has no nix.conf.
  nix.enable = false;

  # Apps installed by Homebrew rather than Nix -- per-machine by nature.
  homebrew.casks = pkgs.callPackage ../../modules/darwin/casks.nix { };

  local.dock.entries = [
    { path = "/Applications/Slack.app/"; }
    { path = "/System/Applications/Messages.app/"; }
    { path = "${pkgs.alacritty}/Applications/Alacritty.app/"; }
    { path = "/System/Applications/Music.app/"; }
    { path = "/Applications/Google Chrome.app/"; }
    { path = "/Applications/Visual Studio Code.app/"; }
    { path = "/Applications/Claude.app/"; }
    { path = "/Applications/Discord.app/"; }
    {
      path = "${config.users.users.${user}.home}/.local/share/";
      section = "others";
      options = "--sort name --view grid --display folder";
    }
    {
      path = "${config.users.users.${user}.home}/.local/share/downloads";
      section = "others";
      options = "--sort name --view grid --display stack";
    }
  ];

  # Codex (Rust/rustls) trusts the Obsidian Local REST API's self-signed cert.
  # It reads CODEX_CA_CERTIFICATE, which is ADDITIVE to the native root store,
  # so this cannot affect trust for any other connection. Set via launchd so
  # the ChatGPT.app GUI inherits it -- it is not started from a shell, and
  # `launchctl setenv` does not survive a reboot.
  # NB: the cert expires 2027-06-14; ~/.codex/scripts/obsidian_ca_env.sh
  # re-exports it from the Obsidian plugin config when it rotates.
  #
  # Host-specific: the pem is generated by the Obsidian install on this Mac.
  launchd.user.envVariables.CODEX_CA_CERTIFICATE =
    "/Users/${user}/.claude/obsidian-local-rest-api.pem";

  # dsh (DeepSeek Harness) web UI. Owned by launchd rather than a shell so it
  # survives terminal exits and logouts, and KeepAlive restarts it if it dies.
  # ThrottleInterval stops a missing/broken npm tree from hot-looping.
  # WorkingDirectory is the agent's workspace root -- deliberately a dedicated
  # empty dir, since the harness ships bash and filesystem tools and would
  # otherwise take whatever directory it was launched from.
  # See modules/darwin/packages.nix for why node needs --expose-internals.
  #
  # Host-specific: points at an imperative npm tree under ~/.local/share/dsh.
  launchd.user.agents.dsh-web = {
    serviceConfig = {
      RunAtLoad = true;
      KeepAlive = true;
      ThrottleInterval = 30;
      WorkingDirectory = "/Users/${user}/dsh-workspace";
      StandardOutPath = "/tmp/dsh-web.out.log";
      StandardErrorPath = "/tmp/dsh-web.err.log";
      ProgramArguments = [
        "/bin/sh"
        "-c"
        "exec ${pkgs.nodejs_22}/bin/node --expose-internals \"$HOME/.local/share/dsh/node_modules/@deepseek-ai/dsh/lib/bin.js\" web --no-open --port 3080"
      ];
    };
  };

  home-manager.users.${user} = { config, lib, ... }: {
    home.file = {
      # Clean-named shortcuts to cloud sync roots.
      #
      # mkOutOfStoreSymlink is essential here: a plain `source` would try to
      # copy the target into the nix store, which for a live cloud folder
      # would be catastrophic. This emits a direct symlink to the real path.
      #
      # The sync roots themselves are NEVER renamed -- OneDrive's lives under
      # ~/Library/CloudStorage and is managed by the macOS File Provider API,
      # and Nutstore records its root path in ~/.nutstore/db/nutstore.db.
      # These are additive aliases only.
      #
      # Host-specific: these are this machine's Purdue and Nutstore accounts.
      "Purdue_OneDrive".source = config.lib.file.mkOutOfStoreSymlink
        "${config.home.homeDirectory}/Library/CloudStorage/OneDrive-purdue.edu";

      "Nutstore".source = config.lib.file.mkOutOfStoreSymlink
        "${config.home.homeDirectory}/NutstoreFiles/Nutstore";
    };

    # Squat the path OneDrive uses for its own home-folder shortcut, so
    # the space-laden "OneDrive - purdue.edu" cannot come back after an
    # app update. OneDrive exposes no preference to disable it.
    #
    # A 0-byte file with uchg makes OneDrive's unlink() fail with EPERM,
    # and its symlink() then fails with EEXIST. `hidden` keeps it out of
    # Finder. Use ~/Purdue_OneDrive (declared above) instead.
    #
    # To undo:  chflags nouchg ~/"OneDrive - purdue.edu" && rm ~/"OneDrive - purdue.edu"
    home.activation.onedriveShortcutTombstone =
      lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        p="$HOME/OneDrive - purdue.edu"
        # Only ever replace a symlink or nothing -- never a real file.
        if [ -L "$p" ] || [ ! -e "$p" ]; then
          /usr/bin/chflags nouchg "$p" 2>/dev/null || true
          rm -f "$p" || true
          touch "$p" || true
        fi
        /usr/bin/chflags uchg,hidden "$p" 2>/dev/null || true
      '';
  };
}
