# Runxi's MacBook Pro. Everything here is true of THIS machine, not of "a Mac":
# the apps actually installed on it, its dock, its cloud-sync accounts, and the
# launchd agents for tools that live outside the Nix store on this box.
#
# Settings that should hold on every Mac live in ./default.nix.
#
# Account name is `runxishen` (uid 501, pre-dates the fleet's `rshen`
# convention). It is threaded in from mkDarwin rather than written here, so
# renaming this machine later means editing one string in flake.nix.
{ config, pkgs, lib, user, ... }:

{
  imports = [
    # Purdue OneDrive: the ~/Purdue_OneDrive alias and the tombstone that keeps
    # "OneDrive - purdue.edu" from ever appearing. Shared with rshen-mbp, which
    # signs into the same tenant.
    ../../modules/darwin/onedrive-purdue.nix
  ];

  # This Mac runs Determinate Nix, which manages its own daemon; nix-darwin must
  # keep its hands off. A machine installed with the upstream Nix installer
  # wants `true` instead, which is why this is per-host rather than shared.
  # Verified: /run/current-system/etc has no nix.conf.
  nix.enable = false;

  # Apps installed by Homebrew rather than Nix -- per-machine by nature.
  homebrew.casks = pkgs.callPackage ../../modules/darwin/casks.nix { };

  local.dock.entries = [
    { path = "/Applications/Slack.app/"; }
    { path = "/System/Applications/Messages.app/"; }
    { path = "${pkgs.alacritty}/Applications/Alacritty.app/"; }
    { path = "/System/Applications/Music.app/"; }
    { path = "/Applications/Google Chrome.app/"; }
    { path = "/Applications/Visual Studio Code.app/"; }
    { path = "/Applications/Claude.app/"; }
    { path = "/Applications/Discord.app/"; }
    {
      path = "${config.users.users.${user}.home}/.local/share/";
      section = "others";
      options = "--sort name --view grid --display folder";
    }
    {
      path = "${config.users.users.${user}.home}/.local/share/downloads";
      section = "others";
      options = "--sort name --view grid --display stack";
    }
  ];

  # Codex (Rust/rustls) trusts the Obsidian Local REST API's self-signed cert.
  # It reads CODEX_CA_CERTIFICATE, which is ADDITIVE to the native root store,
  # so this cannot affect trust for any other connection. Set via launchd so
  # the ChatGPT.app GUI inherits it -- it is not started from a shell, and
  # `launchctl setenv` does not survive a reboot.
  # NB: the cert expires 2027-06-14; ~/.codex/scripts/obsidian_ca_env.sh
  # re-exports it from the Obsidian plugin config when it rotates.
  #
  # Host-specific: the pem is generated by the Obsidian install on this Mac.
  launchd.user.envVariables.CODEX_CA_CERTIFICATE =
    "/Users/${user}/.claude/obsidian-local-rest-api.pem";

  # dsh (DeepSeek Harness) web UI. Owned by launchd rather than a shell so it
  # survives terminal exits and logouts, and KeepAlive restarts it if it dies.
  # ThrottleInterval stops a missing/broken npm tree from hot-looping.
  # WorkingDirectory is the agent's workspace root -- deliberately a dedicated
  # empty dir, since the harness ships bash and filesystem tools and would
  # otherwise take whatever directory it was launched from.
  # See modules/darwin/packages.nix for why node needs --expose-internals.
  #
  # Host-specific: points at an imperative npm tree under ~/.local/share/dsh.
  launchd.user.agents.dsh-web = {
    serviceConfig = {
      RunAtLoad = true;
      KeepAlive = true;
      ThrottleInterval = 30;
      WorkingDirectory = "/Users/${user}/dsh-workspace";
      StandardOutPath = "/tmp/dsh-web.out.log";
      StandardErrorPath = "/tmp/dsh-web.err.log";
      ProgramArguments = [
        "/bin/sh"
        "-c"
        "exec ${pkgs.nodejs_22}/bin/node --expose-internals \"$HOME/.local/share/dsh/node_modules/@deepseek-ai/dsh/lib/bin.js\" web --no-open --port 3080"
      ];
    };
  };

  home-manager.users.${user} = { config, lib, ... }: {
    # Clean-named shortcut to this machine's Nutstore sync root.
    #
    # mkOutOfStoreSymlink is essential here: a plain `source` would try to copy
    # the target into the nix store, which for a live cloud folder would be
    # catastrophic. This emits a direct symlink to the real path.
    #
    # The sync root itself is NEVER renamed -- Nutstore records its path in
    # ~/.nutstore/db/nutstore.db. This is an additive alias only.
    #
    # Host-specific: Nutstore is installed on this Mac only. rshen-mbp reaches
    # the same account over WebDAV (Zotero's file sync) and needs no client.
    # The Purdue OneDrive alias that used to live here moved to
    # modules/darwin/onedrive-purdue.nix when the second Mac grew it too.
    home.file."Nutstore".source = config.lib.file.mkOutOfStoreSymlink
      "${config.home.homeDirectory}/NutstoreFiles/Nutstore";
  };
}
